# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Endavours in software stuff
title: Endavours in software stuff
email: maschmi@maschmi.net
description: >- # this means to ignore newlines until "baseurl:"
  Most, if not all of the post, will have to do somehing with software development. Expect it to be a mixture between
  techy stuff, meta stuff and the way we work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.maschmi.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  maschmi
include: ["_pages"]
permalink: /:title/

# Build settings
remote_theme: wowthemesnet/mediumish-theme-jekyll
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-remote-theme
  - jekyll-relative-links
  - kramdown
  - kramdown-parser-gfm
  - rouge

lsi: false
safe: true
source: https://github.com/maschmi/maschmi.github.io
incremental: false
highlighter: rouge
markdown: kramdown
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Pagination
paginate: 6
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - .fleet/
